// <auto-generated />
using System;
using System.Collections.Generic;
using JobFinder.Api.Common.Models;
using JobFinder.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobFinder.Api.Data.Migrations
{
    [DbContext(typeof(JobFinderDbContext))]
    [Migration("20260628070421_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ApplicationStatus", new[] { "submitted", "shortlisted", "rejected", "under_review" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "NotificationType", new[] { "application_update", "system" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ReportStatus", new[] { "open", "reviewed", "dismissed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "Role", new[] { "job_seeker", "recruiter", "admin" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobFinder.Api.Data.Entities.Application", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text")
                        .HasColumnName("coverLetter");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jobId");

                    b.Property<string>("JobSeekerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jobSeekerId");

                    b.Property<ApplicationStatus>("Status")
                        .HasColumnType("\"ApplicationStatus\"")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("JobSeekerId");

                    b.HasIndex("JobId", "JobSeekerId")
                        .IsUnique();

                    b.ToTable("Application");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.Job", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("RecruiterId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recruiterId");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("text")
                        .HasColumnName("salaryRange");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsActive", "Category");

                    b.HasIndex("IsActive", "CreatedAt");

                    b.HasIndex("RecruiterId", "CreatedAt");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.JobSeekerProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Education")
                        .HasColumnType("text")
                        .HasColumnName("education");

                    b.Property<string>("Experience")
                        .HasColumnType("text")
                        .HasColumnName("experience");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("ResumeUrl")
                        .HasColumnType("text")
                        .HasColumnName("resumeUrl");

                    b.PrimitiveCollection<List<string>>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skills");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("JobSeekerProfile");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("isRead");

                    b.Property<NotificationType>("Type")
                        .HasColumnType("\"NotificationType\"")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.RecruiterProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("companyName");

                    b.Property<string>("CompanyWebsite")
                        .HasColumnType("text")
                        .HasColumnName("companyWebsite");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Industry")
                        .HasColumnType("text")
                        .HasColumnName("industry");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RecruiterProfile");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ReportedJobId")
                        .HasColumnType("text")
                        .HasColumnName("reportedJobId");

                    b.Property<string>("ReportedUserId")
                        .HasColumnType("text")
                        .HasColumnName("reportedUserId");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reporterId");

                    b.Property<ReportStatus>("Status")
                        .HasColumnType("\"ReportStatus\"")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ReportedJobId");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.SavedJob", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jobId");

                    b.Property<string>("JobSeekerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jobSeekerId");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("savedAt");

                    b.HasKey("Id");

                    b.HasIndex("JobSeekerId");

                    b.HasIndex("JobId", "JobSeekerId")
                        .IsUnique();

                    b.ToTable("SavedJob");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.PrimitiveCollection<List<Role>>("Roles")
                        .IsRequired()
                        .HasColumnType("\"Role\"[]")
                        .HasColumnName("roles");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.Application", b =>
                {
                    b.HasOne("JobFinder.Api.Data.Entities.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFinder.Api.Data.Entities.JobSeekerProfile", "JobSeeker")
                        .WithMany("Applications")
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("JobSeeker");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.Job", b =>
                {
                    b.HasOne("JobFinder.Api.Data.Entities.RecruiterProfile", "Recruiter")
                        .WithMany("Jobs")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.JobSeekerProfile", b =>
                {
                    b.HasOne("JobFinder.Api.Data.Entities.User", "User")
                        .WithOne("JobSeeker")
                        .HasForeignKey("JobFinder.Api.Data.Entities.JobSeekerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.Notification", b =>
                {
                    b.HasOne("JobFinder.Api.Data.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.RecruiterProfile", b =>
                {
                    b.HasOne("JobFinder.Api.Data.Entities.User", "User")
                        .WithOne("Recruiter")
                        .HasForeignKey("JobFinder.Api.Data.Entities.RecruiterProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.Report", b =>
                {
                    b.HasOne("JobFinder.Api.Data.Entities.Job", "ReportedJob")
                        .WithMany("Reports")
                        .HasForeignKey("ReportedJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobFinder.Api.Data.Entities.User", "ReportedUser")
                        .WithMany("ReportsReceived")
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobFinder.Api.Data.Entities.User", "Reporter")
                        .WithMany("ReportsMade")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedJob");

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.SavedJob", b =>
                {
                    b.HasOne("JobFinder.Api.Data.Entities.Job", "Job")
                        .WithMany("SavedBy")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFinder.Api.Data.Entities.JobSeekerProfile", "JobSeeker")
                        .WithMany("SavedJobs")
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("JobSeeker");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Reports");

                    b.Navigation("SavedBy");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.JobSeekerProfile", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("SavedJobs");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.RecruiterProfile", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("JobFinder.Api.Data.Entities.User", b =>
                {
                    b.Navigation("JobSeeker");

                    b.Navigation("Notifications");

                    b.Navigation("Recruiter");

                    b.Navigation("ReportsMade");

                    b.Navigation("ReportsReceived");
                });
#pragma warning restore 612, 618
        }
    }
}
